# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Taskctl < Formula
  desc "Process-oriented task management system"
  homepage "https://github.com/name-isname/tasker"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/name-isname/tasker/releases/download/v0.2.1/tasker_0.2.1_darwin_amd64.tar.gz"
      sha256 "baae9276a937eab48b6bdc4435152f41783dac8602789b7a1c3eb03ffd3275ca"

      define_method(:install) do
        bin.install "taskctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/name-isname/tasker/releases/download/v0.2.1/tasker_0.2.1_darwin_arm64.tar.gz"
      sha256 "baffcbf58f19f5059d87140ebdd0533911e6d1c8e6030836df2e3bdd84481699"

      define_method(:install) do
        bin.install "taskctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/name-isname/tasker/releases/download/v0.2.1/tasker_0.2.1_linux_amd64.tar.gz"
      sha256 "0eeafbb73b09ab9d6cb7556d1e80f6f4091cc186049d96931370b718c37c88ad"
      define_method(:install) do
        bin.install "taskctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/name-isname/tasker/releases/download/v0.2.1/tasker_0.2.1_linux_arm64.tar.gz"
      sha256 "0baef60b525bcf7e3b112a9c22217cc0a28b49d2691c002a9d0abad013586fb6"
      define_method(:install) do
        bin.install "taskctl"
      end
    end
  end

  test do
    system "#{bin}/taskctl", "version"
  end
end
