# This file was generated by GoReleaser. DO NOT EDIT.
cask "taskctl" do
  version "0.2.2"

  on_macos do
    on_intel do
      url "https://github.com/name-isname/tasker/releases/download/v#{version}/tasker_#{version}_darwin_amd64.tar.gz"
      sha256 "3c5a4e7540a8743d9329049aa3d5771461d8dded2129073b2f46e319d1d0409c"
    end
    on_arm do
      url "https://github.com/name-isname/tasker/releases/download/v#{version}/tasker_#{version}_darwin_arm64.tar.gz"
      sha256 "253795a061647575e18508e9f9aa4ee344cbf052ff0d48e35c21973676a06694"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/name-isname/tasker/releases/download/v#{version}/tasker_#{version}_linux_amd64.tar.gz"
      sha256 "4858c1b4488868665c53aae730a0e6e58dfe4acff1267b80c2efea199ebbdb08"
    end
    on_arm do
      url "https://github.com/name-isname/tasker/releases/download/v#{version}/tasker_#{version}_linux_arm64.tar.gz"
      sha256 "abc012b26bb6fc330348163302523d32925cff20a0890023d106c6608164009a"
    end
  end

  name "taskctl"
  desc "Process-oriented task management system"
  homepage "https://github.com/name-isname/tasker"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "taskctl"

  # No zap stanza required

end
