# This file was generated by GoReleaser. DO NOT EDIT.
cask "taskctl" do
  version "0.2.6"

  on_macos do
    on_intel do
      url "https://github.com/name-isname/tasker/releases/download/v#{version}/tasker_#{version}_darwin_amd64.tar.gz"
      sha256 "2cf3fc5f00ee6a1b0fe87c9da2c1e3b86aa7d1b6e691f101b4dbc1e15f3c52f0"
    end
    on_arm do
      url "https://github.com/name-isname/tasker/releases/download/v#{version}/tasker_#{version}_darwin_arm64.tar.gz"
      sha256 "3a2657d51b6ea6aa24335d438979f1d7edd940e7cabd3d8649f518541af21fc0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/name-isname/tasker/releases/download/v#{version}/tasker_#{version}_linux_amd64.tar.gz"
      sha256 "0f6e958b1874187516b728fbfb9fa36f15749febebd4810e882805c54477b8f6"
    end
    on_arm do
      url "https://github.com/name-isname/tasker/releases/download/v#{version}/tasker_#{version}_linux_arm64.tar.gz"
      sha256 "66a274cc9735bbd355d19603428307173cc1b72e5a3c6b8a860c35cd1508ae0e"
    end
  end

  name "taskctl"
  desc "Process-oriented task management system"
  homepage "https://github.com/name-isname/tasker"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "taskctl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/taskctl"]
    end
  end

  # No zap stanza required

end
