# This file was generated by GoReleaser. DO NOT EDIT.
cask "taskctl" do
  version "0.2.7"

  on_macos do
    on_intel do
      url "https://github.com/name-isname/tasker/releases/download/v#{version}/tasker_#{version}_darwin_amd64.tar.gz"
      sha256 "22a82ed9c1cf5087d05f531a9916686bef9bbda5ea50c570659503e7994f3ec6"
    end
    on_arm do
      url "https://github.com/name-isname/tasker/releases/download/v#{version}/tasker_#{version}_darwin_arm64.tar.gz"
      sha256 "47de581f1bb84967f50497e186c48c37ac6fed2cd4fd56ef41ed3e09c336d471"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/name-isname/tasker/releases/download/v#{version}/tasker_#{version}_linux_amd64.tar.gz"
      sha256 "63f3f9917ea8f67c2b79ae53b358e9792c2571e9c77867bc8bd6bd65877a8d7c"
    end
    on_arm do
      url "https://github.com/name-isname/tasker/releases/download/v#{version}/tasker_#{version}_linux_arm64.tar.gz"
      sha256 "12d5525595df8d921afc5518e52107389c86512fa9fa9e81f29293b3fda299ef"
    end
  end

  name "taskctl"
  desc "Process-oriented task management system"
  homepage "https://github.com/name-isname/tasker"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "taskctl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/taskctl"]
    end
  end

  # No zap stanza required

end
